### ISSUE TITLE
Undefined should be valid value for first element of sub-arrays

### ISSUE THREAD

**Issue by adius** [adius/shaven#18]

**Comment by naomik** [comment]
I assume this is for things like

```js
['div#pagination', [
  renderPrev(),
  renderNext()
]]
```

Where `renderPrev()` might return `undefined` if there is no <kbd>Prev</kbd> button to display. I.e., the user is already on page 1.

What other circumstance would `undefined` be OK?

**Comment by adius** [comment]
I was just about to implement this, but realized this is maybe not a good idea
as it's not clear if it's really supposed to be a sub-array.

E.g. Was this
```js
['article',
  [
    undefined,
    ['p'],
    ['p']
  ]
]
```
supposed to mean

```js
['article',
  [
    ['p'],
    ['p'],
    ['p']
  ]
]
```

or

```js
['article',
  ['section',
    ['p'],
    ['p']
  ]
]
```

I'd rather think option 2. So the `undefined` should be an error.
If one wants to make sure that the array contains no `undefined`,
it can simply be prevented with `array.filter(element => Boolean(element))`
