### ISSUE TITLE
bower_components folder

### ISSUE THREAD

**Issue by ilmente** [adius/shaven#26]
Hi @adius,
my congratulations for your amazing work!

I'd like to ask you if you can remove `bower_components` folder from your `npm` repo using a `.npmignore` file.
Currently, when I download the module, I get that folder as well. From legal prospective it means that I have to check that folder manually searching for external components and their licenses. 
Indeed, I'm scanning my private commercial repo (in which I use your module) for FOSS I have to declare before selling, and having that folder is blocking me.

Otherwise, I'd just ask you to add a `bower.json` file as a *ad hoc* solution instead of having external code libraries, or (maybe better) add everything to `package.json` as dependencies or devDependencies.

Let me know.
Thanks.
Best.

**Comment by adius** [comment]
Thank you @ilmente for your help! =)

You're totally right! I wanted to remove bower_components long ago, but as the website is hosted with GitHub pages, the frontend js scripts must be included in the repo.
I guess I should finally just split the repo into core and website.
Until then npmignoring is a good idea!

**Comment by ilmente** [comment]
Hope not to bother you too much: can you update the module even on `npm` registry? So I'll be fine.
Thanks a lot.

**Comment by adius** [comment]
Oh, thanks for noticing. I had a wrong description on how to publish it. Fixed it and published it!
Btw:
You said you're scanning your commercial repo.
Are there any tools you can recommend for this task?
Cause that's something I have to do as well in another project.
Or is it simply greping =P

**Comment by abelspry** [comment]
(This is my work-account :) ) Well, I did a tool by myself. The legal issue is very delicate, and I don't want to have problems at all. In my case, we're using `npm` for frontend and `composer` for backend, so it's relatively easy to do, just searching for licenses in manifests or phisical files. Globbing around.

**Comment by adius** [comment]
Can I check out the tool somewhere? =)

**Comment by abelspry** [comment]
Sorry, not at the moment. It's not public yet.
I may write an article about it: if you have patience, I can do it in next days, removing every company implication.

**Comment by adius** [comment]
Sounds great! 😊
